name: DrMap
version: ${project.version}
main: org.acornmc.drmap.DrMap
api-version: 1.16
authors: [DrBot]
commands:
  drmap:
    description: create or reload
    permission: drmap.command
    usage: /<command> create <url>\n/<command> reload
permissions:
  drmap.create:
    default: op
    description: create permission
    children:
      drmap.command: true
  drmap.reload:
    default: op
    description: reload permission
    children:
      drmap.command: true
  drmap.place:
    default: op
    description: place drmaps in item frames
  drmap.rotate:
    default: op
    description: rotate drmaps